services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n.onrender.com
      - key: N8N_ENCRYPTION_KEY
        value: Farzaneh1931
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: sepandads
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Ah@791111101
